'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Status='todo'|'doing'|'done'; type Priority='low'|'medium'|'high';
type Task={id:string;title:string;note:string;dueDate:string|null;priority:Priority;tags:string[];status:Status;position:number;completedAt:string|null;archived:boolean;createdAt:string;updatedAt:string};
type Draft={title:string;note:string;dueDate:string;priority:Priority;tags:string;status:Status};
const empty:Draft={title:'',note:'',dueDate:'',priority:'medium',tags:'',status:'todo'};
const columns:{key:Status;title:string;tone:string}[]=[{key:'todo',title:'待办',tone:'wine'},{key:'doing',title:'进行中',tone:'green'},{key:'done',title:'已完成',tone:'ink'}];
const pLabel={low:'低',medium:'中',high:'高'}; const statusLabel={todo:'待办',doing:'进行中',done:'已完成'};
const isoToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateText=(date:string|null)=>!date?'无日期':date===isoToday()?'今天':new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric'}).format(new Date(`${date}T12:00:00`));

export default function TaskBoard({displayName,signOutPath}:{displayName:string;signOutPath:string}){
 const [tasks,setTasks]=useState<Task[]>([]),[archived,setArchived]=useState<Task[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [dialog,setDialog]=useState<'edit'|'archive'|null>(null),[editing,setEditing]=useState<Task|null>(null),[draft,setDraft]=useState<Draft>(empty);
 const [filter,setFilter]=useState('all'),[tagFilter,setTagFilter]=useState(''),[notice,setNotice]=useState(''),[dragged,setDragged]=useState<string|null>(null);
 const notify=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(''),2800)};
 useEffect(()=>{let active=true;fetch('/api/tasks').then(res=>{if(!res.ok)throw new Error();return res.json()}).then(data=>{if(active)setTasks(data.tasks)}).catch(()=>{if(active)notify('任务没有加载成功，请稍后重试。')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const today=isoToday();
 const visible=useMemo(()=>tasks.filter(t=>{if(filter==='today'&&t.dueDate!==today)return false;if(filter==='week'){if(!t.dueDate)return false;const diff=(new Date(t.dueDate).getTime()-new Date(today).getTime())/86400000;if(diff<0||diff>7)return false}if(filter==='high'&&t.priority!=='high')return false;if(tagFilter&&!t.tags.includes(tagFilter))return false;return true}),[tasks,filter,tagFilter,today]);
 const allTags=useMemo(()=>[...new Set(tasks.flatMap(t=>t.tags))],[tasks]);
 const dueToday=tasks.filter(t=>t.dueDate===today&&t.status!=='done').length,overdue=tasks.filter(t=>t.dueDate&&t.dueDate<today&&t.status!=='done').length;
 const doneToday=tasks.filter(t=>t.completedAt?.slice(0,10)===new Date().toISOString().slice(0,10)).length,totalToday=tasks.filter(t=>t.dueDate===today).length;
 const openCreate=(status:Status='todo')=>{setEditing(null);setDraft({...empty,status});setDialog('edit')};
 const openEdit=(task:Task)=>{setEditing(task);setDraft({title:task.title,note:task.note,dueDate:task.dueDate||'',priority:task.priority,tags:task.tags.join('，'),status:task.status});setDialog('edit')};
 const request=async(body:Record<string,unknown>)=>{const res=await fetch('/api/tasks',{method:body.id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'保存失败');return data.task as Task};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!draft.title.trim())return;setSaving(true);try{const body={...(editing?{id:editing.id}:{}),title:draft.title,note:draft.note,dueDate:draft.dueDate||null,priority:draft.priority,tags:draft.tags.split(/[，,]/).map(x=>x.trim()).filter(Boolean),status:draft.status};const task=await request(body);setTasks(prev=>editing?prev.map(t=>t.id===task.id?task:t):[...prev,task]);setDialog(null);notify(editing?'任务已经更新。':'新任务已经写下。')}catch(e){notify(e instanceof Error?e.message:'保存失败')}finally{setSaving(false)}};
 const mutate=async(task:Task,changes:Partial<Task>,message:string)=>{const before=tasks;setTasks(prev=>prev.map(t=>t.id===task.id?{...t,...changes}:t));try{const updated=await request({id:task.id,...changes});setTasks(prev=>prev.map(t=>t.id===task.id?updated:t));notify(message)}catch{setTasks(before);notify('保存失败，已恢复原来的状态。')}};
 const move=(task:Task,status:Status)=>void mutate(task,{status},status==='done'?'完成得漂亮。':'任务状态已经更新。');
 const drop=(status:Status)=>{const task=tasks.find(t=>t.id===dragged);setDragged(null);if(task&&task.status!==status)move(task,status)};
 const openArchive=async()=>{setDialog('archive');try{const res=await fetch('/api/tasks?archived=true');const data=await res.json();if(!res.ok)throw new Error();setArchived(data.tasks)}catch{notify('归档没有加载成功。')}};
 const archiveTask=async(task:Task)=>{await mutate(task,{archived:true},'任务已归档。');setTasks(prev=>prev.filter(t=>t.id!==task.id))};
 const restore=async(task:Task)=>{try{const restored=await request({id:task.id,archived:false});setArchived(prev=>prev.filter(t=>t.id!==task.id));setTasks(prev=>[...prev,restored]);notify('任务已恢复。')}catch{notify('恢复失败，请重试。')}};
 const remove=async(task:Task)=>{if(!confirm(`永久删除“${task.title}”？此操作无法撤销。`))return;const res=await fetch(`/api/tasks?id=${encodeURIComponent(task.id)}`,{method:'DELETE'});if(res.ok){setArchived(prev=>prev.filter(t=>t.id!==task.id));notify('任务已永久删除。')}else notify('删除失败，请重试。')};
 return <main className="site-shell">
  <header className="topbar"><a className="brand" href="#">纸上日程 <i>·</i></a><p>把要紧的事，安静地做完</p><div className="account"><span>{displayName}</span><a className="avatar" href={signOutPath} aria-label="退出登录">{displayName.slice(0,1)}</a></div></header>
  <section className="intro"><div><span className="eyebrow">{new Intl.DateTimeFormat('en-US',{weekday:'long',day:'2-digit',month:'long'}).format(new Date()).toUpperCase()}</span><h1>今日，留一点<br/><em>从容</em>给自己。</h1></div><button className="add-button" onClick={()=>openCreate()}><span>＋</span> 写下一件事</button></section>
  <section className="today" aria-label="今日概览"><div className="today-title"><span>今日</span><small>TODAY&apos;S NOTES</small></div><div className="metric"><strong>{dueToday}</strong><span>今日到期</span></div><div className="metric overdue"><strong>{overdue}</strong><span>已经逾期</span></div><div className="progress-copy"><span>今日完成度</span><b>{doneToday} / {Math.max(totalToday,doneToday)}</b><div className="progress"><i style={{width:`${Math.min(100,doneToday/Math.max(1,totalToday)*100)}%`}}/></div></div><blockquote>“缓慢而坚定，<br/>也是一种抵达。”</blockquote></section>
  <nav className="filters" aria-label="任务筛选">{[['all','全部任务'],['today','今天'],['week','本周'],['high','高优先级']].map(([key,label])=><button className={filter===key?'active':''} onClick={()=>setFilter(key)} key={key}>{label}{key==='all'&&<span>{tasks.length}</span>}</button>)}<select aria-label="按标签筛选" value={tagFilter} onChange={e=>setTagFilter(e.target.value)}><option value="">所有标签</option>{allTags.map(t=><option key={t}>{t}</option>)}</select><button className="filter-more" onClick={openArchive}>归档 · {archived.length||'···'}</button></nav>
  {loading?<div className="loading">正在翻开你的日程…</div>:<section className="board">{columns.map(column=><div className={`column ${column.tone}`} key={column.key} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(column.key)}><header><div><i/><h2>{column.title}</h2><span>{visible.filter(t=>t.status===column.key).length}</span></div><button onClick={()=>openCreate(column.key)} aria-label={`添加${column.title}任务`}>＋</button></header><div className="cards">{visible.filter(t=>t.status===column.key).sort((a,b)=>a.position-b.position).map(task=><article className={`task-card ${task.status==='done'?'completed':''}`} draggable onDragStart={()=>setDragged(task.id)} onDragEnd={()=>setDragged(null)} key={task.id}><div className="card-top"><span className={`priority ${task.priority==='high'?'hot':''}`}>{pLabel[task.priority]}优先级</span><button onClick={()=>openEdit(task)} aria-label={`编辑${task.title}`}>编辑</button></div><h3>{task.title}</h3>{task.note&&<p>{task.note}</p>}<div className="tags">{task.tags.map(tag=><span key={tag}>#{tag}</span>)}</div><footer><span>◷ &nbsp;{dateText(task.dueDate)}</span><div className="quick-actions"><select aria-label="移动任务" value={task.status} onChange={e=>move(task,e.target.value as Status)}>{columns.map(c=><option value={c.key} key={c.key}>{statusLabel[c.key]}</option>)}</select>{task.status==='done'&&<button onClick={()=>archiveTask(task)}>归档</button>}<span className="drag" title="拖动任务">⠿</span></div></footer></article>)}{visible.filter(t=>t.status===column.key).length===0&&<button className="empty-card" onClick={()=>openCreate(column.key)}>这里还很安静<br/><span>＋ 添加一件事</span></button>}{column.key==='done'&&<button className="archive-hint" onClick={openArchive}>查看已完成与归档 →</button>}</div></div>)}</section>}
  {dialog==='edit'&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><form className="modal" onSubmit={submit}><header><div><small>{editing?'EDIT NOTE':'NEW NOTE'}</small><h2>{editing?'修改这件事':'写下一件事'}</h2></div><button type="button" onClick={()=>setDialog(null)} aria-label="关闭">×</button></header><label>任务标题<input autoFocus required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="比如：读完桌边的那本书"/></label><label>一些备注<textarea maxLength={1000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="写下线索、想法或下一步…"/></label><div className="form-row"><label>截止日期<input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label>优先级<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as Priority})}><option value="low">低</option><option value="medium">中</option><option value="high">高</option></select></label><label>状态<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Status})}>{columns.map(c=><option value={c.key} key={c.key}>{c.title}</option>)}</select></label></div><label>标签<input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})} placeholder="阅读，生活，创作"/><small>用逗号分隔，最多六个</small></label><footer><button type="button" className="quiet" onClick={()=>setDialog(null)}>暂不保存</button><button className="save" disabled={saving}>{saving?'正在保存…':editing?'保存修改':'写进日程'}</button></footer></form></div>}
  {dialog==='archive'&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><section className="modal archive-modal"><header><div><small>ARCHIVE</small><h2>已经收好的日程</h2></div><button onClick={()=>setDialog(null)} aria-label="关闭">×</button></header>{archived.length===0?<div className="archive-empty">这里还没有归档任务。</div>:<div className="archive-list">{archived.map(t=><article key={t.id}><div><h3>{t.title}</h3><span>{dateText(t.dueDate)} · {pLabel[t.priority]}优先级</span></div><div><button onClick={()=>restore(t)}>恢复</button><button className="danger" onClick={()=>remove(t)}>永久删除</button></div></article>)}</div>}</section></div>}
  {notice&&<div className="toast" role="status">{notice}</div>}
 </main>
}
